0:
  label : 'background'
  activated : False
  confidence_threshold : 0.0
1:
  label : 'person'
  activated : True
  confidence_threshold : 0.8
2:
  label : 'bicycle'
  activated : True
  confidence_threshold : 0.15
3:
  label : 'car'
  activated : True
  confidence_threshold : 0.15
4:
  label : 'motorcycle'
  activated : True
  confidence_threshold : 0.15
5:
  label : 'airplane'
  activated : True
  confidence_threshold : 0.15
6:
  label : 'bus'
  activated : True
  confidence_threshold : 0.15
7:
  label : 'train'
  activated : True
  confidence_threshold : 0.15
8:
  label : 'truck'
  activated : True
  confidence_threshold : 0.15
9:
  label : 'boat'
  activated : True
  confidence_threshold : 0.15
10:
  label : 'traffic_light'
  activated : True
  confidence_threshold : 0.15
11:
  label : 'fire_hydrant'
  activated : True
  confidence_threshold : 0.15
12:
  label : 'stop_sign'
  activated : True
  confidence_threshold : 0.15
13:
  label : 'parking_meter'
  activated : True
  confidence_threshold : 0.15
14:
  label : 'bench'
  activated : True
  confidence_threshold : 0.15
15:
  label : 'bird'
  activated : True
  confidence_threshold : 0.15
16:
  label : 'cat'
  activated : True
  confidence_threshold : 0.15
17:
  label : 'dog'
  activated : True
  confidence_threshold : 0.15
18:
  label : 'horse'
  activated : True
  confidence_threshold : 0.15
19:
  label : 'sheep'
  activated : True
  confidence_threshold : 0.15
20:
  label : 'cow'
  activated : True
  confidence_threshold : 0.15
21:
  label : 'elephant'
  activated : True
  confidence_threshold : 0.15
22:
  label : 'bear'
  activated : True
  confidence_threshold : 0.15
23:
  label : 'zebra'
  activated : True
  confidence_threshold : 0.15
24:
  label : 'giraffe'
  activated : True
  confidence_threshold : 0.15
25:
  label : 'backpack'
  activated : True
  confidence_threshold : 0.15
26:
  label : 'umbrella'
  activated : True
  confidence_threshold : 0.15
27:
  label : 'handbag'
  activated : True
  confidence_threshold : 0.15
28:
  label : 'tie'
  activated : True
  confidence_threshold : 0.15
29:
  label : 'suitcase'
  activated : True
  confidence_threshold : 0.15
30:
  label : 'frisbee'
  activated : True
  confidence_threshold : 0.15
31:
  label : 'skis'
  activated : True
  confidence_threshold : 0.15
32:
  label : 'snowboard'
  activated : True
  confidence_threshold : 0.15
33:
  label : 'sports_ball'
  activated : True
  confidence_threshold : 0.15
34:
  label : 'kite'
  activated : True
  confidence_threshold : 0.15
35:
  label : 'baseball_bat'
  activated : True
  confidence_threshold : 0.15
36:
  label : 'baseball_glove'
  activated : True
  confidence_threshold : 0.15
37:
  label : 'skateboard'
  activated : True
  confidence_threshold : 0.15
38:
  label : 'surfboard'
  activated : True
  confidence_threshold : 0.15
39:
  label : 'tennis_racket'
  activated : True
  confidence_threshold : 0.15
40:
  label : 'bottle'
  activated : True
  confidence_threshold : 0.15
41:
  label : 'wine_glass'
  activated : True
  confidence_threshold : 0.15
42:
  label : 'cup'
  activated : True
  confidence_threshold : 0.15
43:
  label : 'fork'
  activated : True
  confidence_threshold : 0.15
44:
  label : 'knife'
  activated : True
  confidence_threshold : 0.15
45:
  label : 'spoon'
  activated : True
  confidence_threshold : 0.15
46:
  label : 'bowl'
  activated : True
  confidence_threshold : 0.15
47:
  label : 'banana'
  activated : True
  confidence_threshold : 0.15
48:
  label : 'apple'
  activated : True
  confidence_threshold : 0.15
49:
  label : 'sandwich'
  activated : True
  confidence_threshold : 0.15
50:
  label : 'orange'
  activated : True
  confidence_threshold : 0.15
51:
  label : 'broccoli'
  activated : True
  confidence_threshold : 0.15
52:
  label : 'carrot'
  activated : True
  confidence_threshold : 0.15
53:
  label : 'hot_dog'
  activated : True
  confidence_threshold : 0.15
54:
  label : 'pizza'
  activated : True
  confidence_threshold : 0.15
55:
  label : 'donut'
  activated : True
  confidence_threshold : 0.15
56:
  label : 'cake'
  activated : True
  confidence_threshold : 0.15
57:
  label : 'chair'
  activated : True
  confidence_threshold : 0.15
58:
  label : 'couch'
  activated : True
  confidence_threshold : 0.15
59:
  label : 'potted_plant'
  activated : True
  confidence_threshold : 0.15
60:
  label : 'bed'
  activated : True
  confidence_threshold : 0.15
61:
  label : 'dining_table'
  activated : True
  confidence_threshold : 0.15
62:
  label : 'toilet'
  activated : True
  confidence_threshold : 0.15
63:
  label : 'tv'
  activated : True
  confidence_threshold : 0.15
64:
  label : 'laptop'
  activated : True
  confidence_threshold : 0.15
65:
  label : 'mouse'
  activated : True
  confidence_threshold : 0.15
66:
  label : 'remote'
  activated : True
  confidence_threshold : 0.15
67:
  label : 'keyboard'
  activated : True
  confidence_threshold : 0.15
68:
  label : 'cell_phone'
  activated : True
  confidence_threshold : 0.15
69:
  label : 'microwave'
  activated : True
  confidence_threshold : 0.15
70:
  label : 'oven'
  activated : True
  confidence_threshold : 0.15
71:
  label : 'toaster'
  activated : True
  confidence_threshold : 0.15
72:
  label : 'sink'
  activated : True
  confidence_threshold : 0.15
73:
  label : 'refrigerator'
  activated : True
  confidence_threshold : 0.15
74:
  label : 'book'
  activated : True
  confidence_threshold : 0.15
75:
  label : 'clock'
  activated : True
  confidence_threshold : 0.15
76:
  label : 'vase'
  activated : True
  confidence_threshold : 0.15
77:
  label : 'scissors'
  activated : True
  confidence_threshold : 0.15
78:
  label : 'teddy_bear'
  activated : True
  confidence_threshold : 0.15
79:
  label : 'hair_drier'
  activated : True
  confidence_threshold : 0.15
80:
  label : 'toothbrush'
  activated : True
  confidence_threshold : 0.15
