0:
  label : 'background'
  activated : False
  confidence_threshold : 0.0
1:
  label : 'person'
  activated : True
  confidence_threshold : 0.8
2:
  label : 'bicycle'
  activated : True
  confidence_threshold : 0.25
3:
  label : 'car'
  activated : True
  confidence_threshold : 0.25
4:
  label : 'motorcycle'
  activated : True
  confidence_threshold : 0.25
5:
  label : 'airplane'
  activated : True
  confidence_threshold : 0.25
6:
  label : 'bus'
  activated : True
  confidence_threshold : 0.25
7:
  label : 'train'
  activated : True
  confidence_threshold : 0.25
8:
  label : 'truck'
  activated : True
  confidence_threshold : 0.25
9:
  label : 'boat'
  activated : True
  confidence_threshold : 0.25
10:
  label : 'traffic_light'
  activated : True
  confidence_threshold : 0.25
11:
  label : 'fire_hydrant'
  activated : True
  confidence_threshold : 0.25
12:
  label : 'stop_sign'
  activated : True
  confidence_threshold : 0.25
13:
  label : 'parking_meter'
  activated : True
  confidence_threshold : 0.25
14:
  label : 'bench'
  activated : True
  confidence_threshold : 0.25
15:
  label : 'bird'
  activated : True
  confidence_threshold : 0.25
16:
  label : 'cat'
  activated : True
  confidence_threshold : 0.25
17:
  label : 'dog'
  activated : True
  confidence_threshold : 0.25
18:
  label : 'horse'
  activated : True
  confidence_threshold : 0.25
19:
  label : 'sheep'
  activated : True
  confidence_threshold : 0.25
20:
  label : 'cow'
  activated : True
  confidence_threshold : 0.25
21:
  label : 'elephant'
  activated : True
  confidence_threshold : 0.25
22:
  label : 'bear'
  activated : True
  confidence_threshold : 0.25
23:
  label : 'zebra'
  activated : True
  confidence_threshold : 0.25
24:
  label : 'giraffe'
  activated : True
  confidence_threshold : 0.25
25:
  label : 'backpack'
  activated : True
  confidence_threshold : 0.25
26:
  label : 'umbrella'
  activated : True
  confidence_threshold : 0.25
27:
  label : 'handbag'
  activated : True
  confidence_threshold : 0.25
28:
  label : 'tie'
  activated : True
  confidence_threshold : 0.25
29:
  label : 'suitcase'
  activated : True
  confidence_threshold : 0.25
30:
  label : 'frisbee'
  activated : True
  confidence_threshold : 0.25
31:
  label : 'skis'
  activated : True
  confidence_threshold : 0.25
32:
  label : 'snowboard'
  activated : True
  confidence_threshold : 0.25
33:
  label : 'sports_ball'
  activated : True
  confidence_threshold : 0.25
34:
  label : 'kite'
  activated : True
  confidence_threshold : 0.25
35:
  label : 'baseball_bat'
  activated : True
  confidence_threshold : 0.25
36:
  label : 'baseball_glove'
  activated : True
  confidence_threshold : 0.25
37:
  label : 'skateboard'
  activated : True
  confidence_threshold : 0.25
38:
  label : 'surfboard'
  activated : True
  confidence_threshold : 0.25
39:
  label : 'tennis_racket'
  activated : True
  confidence_threshold : 0.25
40:
  label : 'bottle'
  activated : True
  confidence_threshold : 0.25
41:
  label : 'wine_glass'
  activated : True
  confidence_threshold : 0.25
42:
  label : 'cup'
  activated : True
  confidence_threshold : 0.25
43:
  label : 'fork'
  activated : True
  confidence_threshold : 0.25
44:
  label : 'knife'
  activated : True
  confidence_threshold : 0.25
45:
  label : 'spoon'
  activated : True
  confidence_threshold : 0.25
46:
  label : 'bowl'
  activated : True
  confidence_threshold : 0.25
47:
  label : 'banana'
  activated : True
  confidence_threshold : 0.4
48:
  label : 'apple'
  activated : True
  confidence_threshold : 0.25
49:
  label : 'sandwich'
  activated : True
  confidence_threshold : 0.25
50:
  label : 'orange'
  activated : True
  confidence_threshold : 0.25
51:
  label : 'broccoli'
  activated : True
  confidence_threshold : 0.25
52:
  label : 'carrot'
  activated : True
  confidence_threshold : 0.25
53:
  label : 'hot_dog'
  activated : True
  confidence_threshold : 0.25
54:
  label : 'pizza'
  activated : True
  confidence_threshold : 0.25
55:
  label : 'donut'
  activated : True
  confidence_threshold : 0.25
56:
  label : 'cake'
  activated : True
  confidence_threshold : 0.25
57:
  label : 'chair'
  activated : True
  confidence_threshold : 0.25
58:
  label : 'couch'
  activated : True
  confidence_threshold : 0.25
59:
  label : 'potted_plant'
  activated : True
  confidence_threshold : 0.25
60:
  label : 'bed'
  activated : True
  confidence_threshold : 0.25
61:
  label : 'dining_table'
  activated : False
  confidence_threshold : 0.25
62:
  label : 'toilet'
  activated : False
  confidence_threshold : 0.25
63:
  label : 'tv'
  activated : False
  confidence_threshold : 0.25
64:
  label : 'laptop'
  activated : True
  confidence_threshold : 0.25
65:
  label : 'mouse'
  activated : True
  confidence_threshold : 0.25
66:
  label : 'remote'
  activated : True
  confidence_threshold : 0.25
67:
  label : 'keyboard'
  activated : False
  confidence_threshold : 0.25
68:
  label : 'cell_phone'
  activated : True
  confidence_threshold : 0.25
69:
  label : 'microwave'
  activated : True
  confidence_threshold : 0.25
70:
  label : 'oven'
  activated : True
  confidence_threshold : 0.25
71:
  label : 'toaster'
  activated : True
  confidence_threshold : 0.25
72:
  label : 'sink'
  activated : False
  confidence_threshold : 0.25
73:
  label : 'refrigerator'
  activated : False
  confidence_threshold : 0.25
74:
  label : 'book'
  activated : True
  confidence_threshold : 0.25
75:
  label : 'clock'
  activated : True
  confidence_threshold : 0.25
76:
  label : 'vase'
  activated : True
  confidence_threshold : 0.25
77:
  label : 'scissors'
  activated : True
  confidence_threshold : 0.25
78:
  label : 'teddy_bear'
  activated : True
  confidence_threshold : 0.25
79:
  label : 'hair_drier'
  activated : True
  confidence_threshold : 0.25
80:
  label : 'toothbrush'
  activated : True
  confidence_threshold : 0.25
