0:
  label : 'background'
  activated : False
  confidence_threshold : 0.0
1:
  label : 'person'
  activated : True
  confidence_threshold : 0.8
2:
  label : 'bicycle'
  activated : False
  confidence_threshold : 0.18
3:
  label : 'car'
  activated : False
  confidence_threshold : 0.18
4:
  label : 'motorcycle'
  activated : False
  confidence_threshold : 0.18
5:
  label : 'airplane'
  activated : False
  confidence_threshold : 0.18
6:
  label : 'bus'
  activated : False
  confidence_threshold : 0.18
7:
  label : 'train'
  activated : False
  confidence_threshold : 0.18
8:
  label : 'truck'
  activated : False
  confidence_threshold : 0.18
9:
  label : 'boat'
  activated : False
  confidence_threshold : 0.18
10:
  label : 'traffic_light'
  activated : False
  confidence_threshold : 0.18
11:
  label : 'fire_hydrant'
  activated : False
  confidence_threshold : 0.18
12:
  label : 'stop_sign'
  activated : False
  confidence_threshold : 0.18
13:
  label : 'parking_meter'
  activated : False
  confidence_threshold : 0.18
14:
  label : 'bench'
  activated : False
  confidence_threshold : 0.18
15:
  label : 'bird'
  activated : False
  confidence_threshold : 0.18
16:
  label : 'cat'
  activated : False
  confidence_threshold : 0.18
17:
  label : 'dog'
  activated : False
  confidence_threshold : 0.18
18:
  label : 'horse'
  activated : False
  confidence_threshold : 0.18
19:
  label : 'sheep'
  activated : False
  confidence_threshold : 0.18
20:
  label : 'cow'
  activated : False
  confidence_threshold : 0.18
21:
  label : 'elephant'
  activated : False
  confidence_threshold : 0.18
22:
  label : 'bear'
  activated : False
  confidence_threshold : 0.18
23:
  label : 'zebra'
  activated : False
  confidence_threshold : 0.18
24:
  label : 'giraffe'
  activated : False
  confidence_threshold : 0.18
25:
  label : 'backpack'
  activated : False
  confidence_threshold : 0.18
26:
  label : 'umbrella'
  activated : False
  confidence_threshold : 0.18
27:
  label : 'handbag'
  activated : False
  confidence_threshold : 0.18
28:
  label : 'tie'
  activated : False
  confidence_threshold : 0.18
29:
  label : 'suitcase'
  activated : False
  confidence_threshold : 0.18
30:
  label : 'frisbee'
  activated : False
  confidence_threshold : 0.18
31:
  label : 'skis'
  activated : False
  confidence_threshold : 0.18
32:
  label : 'snowboard'
  activated : False
  confidence_threshold : 0.18
33:
  label : 'sports_ball'
  activated : False
  confidence_threshold : 0.18
34:
  label : 'kite'
  activated : False
  confidence_threshold : 0.18
35:
  label : 'baseball_bat'
  activated : False
  confidence_threshold : 0.18
36:
  label : 'baseball_glove'
  activated : False
  confidence_threshold : 0.18
37:
  label : 'skateboard'
  activated : False
  confidence_threshold : 0.18
38:
  label : 'surfboard'
  activated : False
  confidence_threshold : 0.18
39:
  label : 'tennis_racket'
  activated : False
  confidence_threshold : 0.18
40:
  label : 'bottle'
  activated : False
  confidence_threshold : 0.18
41:
  label : 'wine_glass'
  activated : False
  confidence_threshold : 0.18
42:
  label : 'cup'
  activated : False
  confidence_threshold : 0.18
43:
  label : 'fork'
  activated : False
  confidence_threshold : 0.18
44:
  label : 'knife'
  activated : False
  confidence_threshold : 0.18
45:
  label : 'spoon'
  activated : False
  confidence_threshold : 0.18
46:
  label : 'bowl'
  activated : False
  confidence_threshold : 0.18
47:
  label : 'banana'
  activated : False
  confidence_threshold : 0.18
48:
  label : 'apple'
  activated : False
  confidence_threshold : 0.18
49:
  label : 'sandwich'
  activated : False
  confidence_threshold : 0.18
50:
  label : 'orange'
  activated : False
  confidence_threshold : 0.18
51:
  label : 'broccoli'
  activated : False
  confidence_threshold : 0.18
52:
  label : 'carrot'
  activated : False
  confidence_threshold : 0.18
53:
  label : 'hot_dog'
  activated : False
  confidence_threshold : 0.18
54:
  label : 'pizza'
  activated : False
  confidence_threshold : 0.18
55:
  label : 'donut'
  activated : False
  confidence_threshold : 0.18
56:
  label : 'cake'
  activated : False
  confidence_threshold : 0.18
57:
  label : 'chair'
  activated : False
  confidence_threshold : 0.18
58:
  label : 'couch'
  activated : False
  confidence_threshold : 0.18
59:
  label : 'potted_plant'
  activated : False
  confidence_threshold : 0.18
60:
  label : 'bed'
  activated : False
  confidence_threshold : 0.18
61:
  label : 'dining_table'
  activated : False
  confidence_threshold : 0.18
62:
  label : 'toilet'
  activated : False
  confidence_threshold : 0.18
63:
  label : 'tv'
  activated : False
  confidence_threshold : 0.18
64:
  label : 'laptop'
  activated : False
  confidence_threshold : 0.18
65:
  label : 'mouse'
  activated : False
  confidence_threshold : 0.18
66:
  label : 'remote'
  activated : False
  confidence_threshold : 0.18
67:
  label : 'keyboard'
  activated : False
  confidence_threshold : 0.18
68:
  label : 'cell_phone'
  activated : False
  confidence_threshold : 0.18
69:
  label : 'microwave'
  activated : False
  confidence_threshold : 0.18
70:
  label : 'oven'
  activated : False
  confidence_threshold : 0.18
71:
  label : 'toaster'
  activated : False
  confidence_threshold : 0.18
72:
  label : 'sink'
  activated : False
  confidence_threshold : 0.18
73:
  label : 'refrigerator'
  activated : False
  confidence_threshold : 0.18
74:
  label : 'book'
  activated : False
  confidence_threshold : 0.18
75:
  label : 'clock'
  activated : False
  confidence_threshold : 0.18
76:
  label : 'vase'
  activated : False
  confidence_threshold : 0.18
77:
  label : 'scissors'
  activated : False
  confidence_threshold : 0.18
78:
  label : 'teddy_bear'
  activated : False
  confidence_threshold : 0.18
79:
  label : 'hair_drier'
  activated : False
  confidence_threshold : 0.18
80:
  label : 'toothbrush'
  activated : False
  confidence_threshold : 0.18
